### ISSUE TITLE
Question: how to pass a hashref to wasmtime?

### ISSUE THREAD

**Issue by aminroosta** [perlwasm/Wasm#74]
Is it possible to pass a hashref to a `.wasm` file (generated from rust code) -
using [interface types](https://github.com/bytecodealliance/wasmtime/issues/677) ?

from the perl side
```perl
foo({ apple => 1, orange => 2});
```

from rust side
```rust
fn foo(args: &HashMap<String, i32>) {
   println!("{:?}", args);
}
```

**Comment by plicease** [comment]
I am not sure since the interface types spec is still largely up in the air.  The intent is once it solidifies, and is implemented in Wasmtime, we will support as many types as possible.
